---
kind: pipeline
name: deploy
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: 2jours/kafkat
    target: production
    tags: ${DRONE_COMMIT}
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ontwikkelen
  when:
    status:
    - success
    - failure
trigger:
  branch:
    include:
    - master
  event:
    exclude:
    - pull_request
---
kind: secret
external_data:
  dockerhub_username:
    path: hidey-hole/drone/dockerhub
    name: username
  dockerhub_password:
    path: hidey-hole/drone/dockerhub
    name: password
  slack_webhook:
    path: hidey-hole/drone/slack
    name: webhook
