---
kind: pipeline
name: deploy
steps:
- name: docker
  image: plugins/docker
  settings:
    repo: 2jours/kafkat
    target: builder
    tags:
    - latest
    - ${DRONE_COMMIT}
    username: 
      from_secret: dockerhub_username
    password: 
      from_secret: dockerhub_password
- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    channel: ontwikkelen
  when:
    status:
    - success
    - failure
trigger:
  branch:
    include:
    - master
  event:
    exclude:
    - pull_request
---
kind: secret
name: dockerhub_username
get:
  path: hidey-hole/drone/dockerhub
  name: username
---
kind: secret
name: dockerhub_password
get:
  path: hidey-hole/drone/dockerhub
  name: password
---
kind: secret
name: slack_webhook
get:
  path: hidey-hole/drone/slack
  name: webhook